// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXyBBkkoPia91XgxsgcMSTLUwY-jnJ1Mw',
    appId: '1:705922554900:web:bf531c61440f1678ff1b01',
    messagingSenderId: '705922554900',
    projectId: 'fir-test-b00a1',
    authDomain: 'fir-test-b00a1.firebaseapp.com',
    databaseURL: 'https://fir-test-b00a1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fir-test-b00a1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcHVB-t2zOw7GBEvui6IkpDtx6Mn7aapU',
    appId: '1:705922554900:android:8ea179fbfe10889aff1b01',
    messagingSenderId: '705922554900',
    projectId: 'fir-test-b00a1',
    databaseURL: 'https://fir-test-b00a1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fir-test-b00a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAS9sNjSmXqUFN4KFhraddIQP58E1QDxg',
    appId: '1:705922554900:ios:6a3400a15617b2f6ff1b01',
    messagingSenderId: '705922554900',
    projectId: 'fir-test-b00a1',
    databaseURL: 'https://fir-test-b00a1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fir-test-b00a1.appspot.com',
    iosClientId: '705922554900-16u69lhbdt8147f9jak37db3bu4o16mn.apps.googleusercontent.com',
    iosBundleId: 'com.example.calorieCalculator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAS9sNjSmXqUFN4KFhraddIQP58E1QDxg',
    appId: '1:705922554900:ios:6a3400a15617b2f6ff1b01',
    messagingSenderId: '705922554900',
    projectId: 'fir-test-b00a1',
    databaseURL: 'https://fir-test-b00a1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fir-test-b00a1.appspot.com',
    iosClientId: '705922554900-16u69lhbdt8147f9jak37db3bu4o16mn.apps.googleusercontent.com',
    iosBundleId: 'com.example.calorieCalculator',
  );
}
